M48
; DRILL file {KiCad 9.0.5} date 2026-02-24T14:51:14-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-24T14:51:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
%
G90
G05
T1
X147.32Y-88.9
T2
X147.32Y-93.4
T3
X236.81Y-92.06
X236.81Y-113.06
T4
X133.35Y-88.9
X133.35Y-114.3
X197.68Y-87.27
X208.86Y-116.38
M30
